### ISSUE TITLE
DLS: Section Components - Accordion - Issues

### ISSUE THREAD

**Issue by lalov1** [utsa-asc/college-dls#226] opened 2022-05-24 20:34 UTC
It seems like when you open an accordion the title disappears and if you open both there are some issues closing them. 

![Image](https://user-images.githubusercontent.com/7785251/170127047-3d6b99cc-ad98-47bf-bc04-4ba4920a6c39.png)

**Comment by garza-utsa** [comment] 2022-05-24 21:17
duplicate of #193

**Closed by garza-utsa** 2022-05-24 21:17 UTC

**Comment by prd409-utsa** [comment] 2022-06-21 16:12
This was fixed in [PR 314](https://github.com/utsa-asc/college-dls/pull/314)
