### ISSUE TITLE
remove border from .highlight-card-img

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#411] opened 2022-07-26 02:40 UTC
it looks like in this class, it is also adding a thin white line around the image. you can see it more when it's on a gray background. could we remove the 1px line around the image?

<img width="353" alt="Screen Shot 2022-07-25 at 9 39 47 PM" src="https://user-images.githubusercontent.com/107521898/180911272-c88f2a05-86a0-4158-8f3e-489bafaaeae6.png">

<img width="358" alt="Screen Shot 2022-07-25 at 9 40 27 PM" src="https://user-images.githubusercontent.com/107521898/180911363-0921664f-b920-40d9-94ff-5a1aec24168d.png">

**Comment by garza-utsa** [comment] 2022-07-26 19:26
ah didn't think to test with grey-bg, which is probably why I was unable to reproduce this bug last week

**Comment by garza-utsa** [comment] 2022-07-26 19:34
@kgarza-utsa  this style definition does not exist in the DLS, it looks like y'all also have a border-bottom orange 6px, which is ending up looking like 12px with our border-top additions from last week

line 266 in esmc.css:
<img width="1322" alt="Screenshot 2022-07-26 at 2 33 49 PM" src="https://user-images.githubusercontent.com/16828076/181096455-53215383-d384-4dc4-b3b3-7eae26cceeb1.png">

**Comment by garza-utsa** [comment] 2022-08-01 15:42
not in the DLS, cannot replicate, closing

**Closed by garza-utsa** 2022-08-01 15:42 UTC
Labels: sass
