### ISSUE TITLE
Call to Action Media

### ISSUE THREAD

**Issue by kgarza-utsa** [utsa-asc/college-dls#351] opened 2022-06-29 03:58 UTC
Hello. I'm still seeing some strange alignments within the elements of the Call to Action Media

I'm not sure what styles are calling this, but on this first example, I noticed this `--bs-gutter-x:1.5rem; `

<img width="873" alt="Screen Shot 2022-06-28 at 10 57 21 PM" src="https://user-images.githubusercontent.com/107521898/176348307-a0776c5e-479e-462a-a56e-3494857e2129.png">

and I couldn't figure out why there is large spacing happening when the text is on the left side

<img width="878" alt="Screen Shot 2022-06-28 at 10 56 28 PM" src="https://user-images.githubusercontent.com/107521898/176348210-98498a5b-63b9-457a-b939-d760ec208e5b.png">

**Comment by garza-utsa** [comment] 2022-06-29 15:37
duplicate of #295

**Closed by garza-utsa** 2022-06-29 15:37 UTC
